import { Navbar } from '@/components/Navbar.jsx';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJS/Prisma - CRUD',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className='h-[calc(100vh-7rem)]'>
          {children}
        </main>
        
      </body>
    </html>
  )
}
